# Ecuaciones diferenciales estocásticas


# Diferenciales

- Diferencial de potencia de $W_t$: Validación numérica de fórmul $d(W_t^p)=p(W_t^{p-2})(W_t dW_t+\frac{p-1}{2}dt)$

In [12]:
#Diferenciales
import numpy as np
import matplotlib.pyplot as plt 
import brownian_motion as bm

T=1
n=101
p=5
t=np.linspace(0,T,n)
dt=T/(n-1)

dW=bm.get_dB(n-1,dt=dt)
W_0=0
W=np.cumsum(dW)
F_t=W**p #Elemento a elemento. Vector del proceso
dF=np.diff
dW



array([ 0.        , -0.19232523, -0.21184974,  0.12764905, -0.13314022,
        0.18065844, -0.0809214 , -0.01134121, -0.04959035,  0.15971758,
        0.06170063,  0.02357141,  0.13469134, -0.03051183,  0.02196059,
        0.10394103,  0.06632349, -0.01295609, -0.12927174,  0.00771083,
        0.09963494, -0.15565584,  0.04407037,  0.04751327, -0.02916367,
        0.05612666, -0.00491069,  0.00345061,  0.18296441, -0.00624007,
       -0.00681372, -0.00327038,  0.15138231,  0.03857981,  0.07079415,
       -0.0284642 ,  0.09909928, -0.01395976, -0.11331994, -0.09933638,
        0.05325619,  0.1753269 , -0.22251388, -0.03698549, -0.08611079,
       -0.09325823,  0.03293887,  0.11092276,  0.08502971, -0.00952573,
       -0.04683831, -0.0215656 ,  0.01814149, -0.04295616,  0.03233652,
       -0.03256786,  0.00089773, -0.07144102, -0.01281896,  0.09073641,
        0.03069853,  0.08359659,  0.06186382, -0.05824859, -0.04263637,
        0.12965408, -0.10845884, -0.06691896,  0.06906938, -0.09

In [13]:
X_t=np.linspace(0,5,6)
#F_t=X_t**2
np.cumsum(X_t)


array([ 0.,  1.,  3.,  6., 10., 15.])

In [21]:
import numpy as np 

bm.get_B_matrix(10,2)
a=np.array([[1,2,3,4],[5,6,7,8]])
a=np.insert(a,0,0,axis=1)
a

array([[0, 1, 2, 3, 4],
       [0, 5, 6, 7, 8]])